name:           JSONisHardItShouldntBe
version:        0.1.0.0
github:         "CaryRock/JSONisHardItShouldntBe"
license:        Unlicense
author:         "Cary Rock"
maintainer:     "carytherock@gmail.com"
copyright:      "2025 Cary Rock"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:    Please see the README on GitHub at <https://github.com/CaryRock/JSONisHardItShouldntBe#readme>

dependencies:
- base >= 4.7 && < 5
- directory >= 1.3
- aeson >= 2.0
- bytestring >= 0.10
- vector >= 0.13.1.0
- text >= 2.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  JSONisHardItShouldntBe:
    main:               Main.hs
    source-dirs:        app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - JSONisHardItShouldntBe
